# ItemBingo default configuration
# These values are also editable in-game via /admin.

team:
  enabled: false

shop:
  enabled: true
  effectShopEnabled: true
  itemShopEnabled: true

vanilla:
  shovelOxidizeCopper: false

game:
  # 0 = TOTAL_SUBMISSION, 1 = LAST_SUBMISSION, 2 = CODEFORCES
  penalty: 0

mode:
  positionSwap: false
